### ISSUE TITLE
Broken Picture

### ISSUE THREAD

**Issue by evanzhu2013** [atom/styleguide#35] opened 2016-04-27 12:45 UTC
As shown below, the icon picture is broken. 

<img width="887" alt="2016-04-27 20 47 49" src="https://cloud.githubusercontent.com/assets/7533756/14852515/591e4fe0-0cb9-11e6-96cf-4aaf76c06a97.png">

I appreciate your contribution, which benefits me a lot. 

Thank you very much!

**Comment by lee-dohm** [comment] 2016-04-27 22:13
This is a duplicate of https://github.com/atom/settings-view/issues/327. You may want to subscribe there for updates.

**Closed by lee-dohm** 2016-04-27 22:13 UTC
