### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/AppData\Local\atom\node_modules\highli...

### ISSUE THREAD

**Issue by ivanoung** [atom/styleguide#59] opened 2017-06-26 04:44 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [styleguide](https://github.com/atom/styleguide) package 0.49.6

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\vaniaoung\AppData\Local\atom\node_modules\highlights\gen\grammars.json'

```
At fs.js:640

Error: ENOENT: no such file or directory, open 'C:\Users\vaniaoung\AppData\Local\atom\node_modules\highlights\gen\grammars.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Proxy.fs.readFileSync (fs.js:508:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at Highlights.module.exports.Highlights.loadGrammarsSync (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/highlights/lib/highlights.js:238:34)
    at Highlights.module.exports.Highlights.highlightSync (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/highlights/lib/highlights.js:40:18)
    at CodeBlock.update (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/styleguide/lib/code-block.js:33:62)
    at new CodeBlock (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/styleguide/lib/code-block.js:23:16)
    at render (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:17:31)
    at addChildren (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:39:30)
    at render (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:29:27)
    at addChildren (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:39:30)
    at render (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/styleguide/node_modules/etch/lib/render.js:29:27)
    at updateChildren (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/styleguide/node_modules/etch/lib/patch.js:109:40)
    at patch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/styleguide/node_modules/etch/lib/patch.js:15:15)
    at updateSync (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/styleguide/node_modules/etch/lib/component-helpers.js:108:26)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/styleguide/node_modules/etch/lib/component-helpers.js:72:13
    at DefaultScheduler.performUpdates (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/styleguide/node_modules/etch/lib/default-scheduler.js:48:40)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-html-preview 0.1.22 
collaboratom 0.2.1 
highlight-selected 0.13.1 
language-liquid 0.6.0 
minimap 4.28.2 
minimap-find-and-replace 4.5.2 
package-sync 1.1.0 
pigments 0.39.1 
pure-syntax 0.2.1 
```

**Comment by rsese** [comment] 2017-06-26 21:21
Thanks for the report!  Can you confirm what you were doing at the time of the error and if it's reproducible?

Also, it looks like a file is missing- can you try re-installing and see if that helps?

**Comment by ivanoung** [comment] 2017-06-27 00:27
Don't really know why, I was just trying to open Atom and it gave me this
error message out of nowhere.

I'll try re-installing it to see if that helps.

Thanks.
Ivan

**Comment by Ben3eeE** [comment] 2017-08-07 08:29
Thank you for your issue!

We haven't gotten a response to our questions in our comment https://github.com/atom/styleguide/issues/59#issuecomment-311185660. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Closed by Ben3eeE** 2017-08-07 08:29 UTC
Labels: more-information-needed

**Comment by przemo** [comment] 2017-09-12 14:57
It occurs even with a clean install on Windows 7, but when the Style Guide Tab was opened before. When it is closed, and you restart Atom, everything looks fine.
